name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "infrastructure/**"

jobs:
  trigger-amplify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Amplify build
        run: curl -sSf -X POST "${{ secrets.AMPLIFY_WEBHOOK_URL }}"
